// <auto-generated>
// This code was generated by a tool.
// LinqToWmi.ClassGenerator Version: 1.0.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if  the code is regenerated.
// </auto-generated>
namespace WmiEntities {
    using System;
    using System.Linq;
    using LinqToWmi.Core.WMI;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LinqToWmi.ClassGenerator", "1.0.0.0")]
    public class Win32_PerfFormattedData_PerfProc_Process {
        
        private string _caption;
        
        private uint _creatingProcessID;
        
        private string _description;
        
        private ulong _elapsedTime;
        
        private ulong _frequency_Object;
        
        private ulong _frequency_PerfTime;
        
        private ulong _frequency_Sys100NS;
        
        private uint _handleCount;
        
        private uint _iDProcess;
        
        private ulong _iODataBytesPersec;
        
        private ulong _iODataOperationsPersec;
        
        private ulong _iOOtherBytesPersec;
        
        private ulong _iOOtherOperationsPersec;
        
        private ulong _iOReadBytesPersec;
        
        private ulong _iOReadOperationsPersec;
        
        private ulong _iOWriteBytesPersec;
        
        private ulong _iOWriteOperationsPersec;
        
        private string _name;
        
        private uint _pageFaultsPersec;
        
        private ulong _pageFileBytes;
        
        private ulong _pageFileBytesPeak;
        
        private ulong _percentPrivilegedTime;
        
        private ulong _percentProcessorTime;
        
        private ulong _percentUserTime;
        
        private uint _poolNonpagedBytes;
        
        private uint _poolPagedBytes;
        
        private uint _priorityBase;
        
        private ulong _privateBytes;
        
        private uint _threadCount;
        
        private ulong _timestamp_Object;
        
        private ulong _timestamp_PerfTime;
        
        private ulong _timestamp_Sys100NS;
        
        private ulong _virtualBytes;
        
        private ulong _virtualBytesPeak;
        
        private ulong _workingSet;
        
        private ulong _workingSetPeak;
        
        /// <summary>
        /// Represents the property Caption
        /// </summary>
        public virtual string Caption {
            get {
                return this._caption;
            }
            set {
                this._caption = value;
            }
        }
        
        /// <summary>
        /// Represents the property CreatingProcessID
        /// </summary>
        public virtual uint CreatingProcessID {
            get {
                return this._creatingProcessID;
            }
            set {
                this._creatingProcessID = value;
            }
        }
        
        /// <summary>
        /// Represents the property Description
        /// </summary>
        public virtual string Description {
            get {
                return this._description;
            }
            set {
                this._description = value;
            }
        }
        
        /// <summary>
        /// Represents the property ElapsedTime
        /// </summary>
        public virtual ulong ElapsedTime {
            get {
                return this._elapsedTime;
            }
            set {
                this._elapsedTime = value;
            }
        }
        
        /// <summary>
        /// Represents the property Frequency_Object
        /// </summary>
        public virtual ulong Frequency_Object {
            get {
                return this._frequency_Object;
            }
            set {
                this._frequency_Object = value;
            }
        }
        
        /// <summary>
        /// Represents the property Frequency_PerfTime
        /// </summary>
        public virtual ulong Frequency_PerfTime {
            get {
                return this._frequency_PerfTime;
            }
            set {
                this._frequency_PerfTime = value;
            }
        }
        
        /// <summary>
        /// Represents the property Frequency_Sys100NS
        /// </summary>
        public virtual ulong Frequency_Sys100NS {
            get {
                return this._frequency_Sys100NS;
            }
            set {
                this._frequency_Sys100NS = value;
            }
        }
        
        /// <summary>
        /// Represents the property HandleCount
        /// </summary>
        public virtual uint HandleCount {
            get {
                return this._handleCount;
            }
            set {
                this._handleCount = value;
            }
        }
        
        /// <summary>
        /// Represents the property IDProcess
        /// </summary>
        public virtual uint IDProcess {
            get {
                return this._iDProcess;
            }
            set {
                this._iDProcess = value;
            }
        }
        
        /// <summary>
        /// Represents the property IODataBytesPersec
        /// </summary>
        public virtual ulong IODataBytesPersec {
            get {
                return this._iODataBytesPersec;
            }
            set {
                this._iODataBytesPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property IODataOperationsPersec
        /// </summary>
        public virtual ulong IODataOperationsPersec {
            get {
                return this._iODataOperationsPersec;
            }
            set {
                this._iODataOperationsPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property IOOtherBytesPersec
        /// </summary>
        public virtual ulong IOOtherBytesPersec {
            get {
                return this._iOOtherBytesPersec;
            }
            set {
                this._iOOtherBytesPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property IOOtherOperationsPersec
        /// </summary>
        public virtual ulong IOOtherOperationsPersec {
            get {
                return this._iOOtherOperationsPersec;
            }
            set {
                this._iOOtherOperationsPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property IOReadBytesPersec
        /// </summary>
        public virtual ulong IOReadBytesPersec {
            get {
                return this._iOReadBytesPersec;
            }
            set {
                this._iOReadBytesPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property IOReadOperationsPersec
        /// </summary>
        public virtual ulong IOReadOperationsPersec {
            get {
                return this._iOReadOperationsPersec;
            }
            set {
                this._iOReadOperationsPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property IOWriteBytesPersec
        /// </summary>
        public virtual ulong IOWriteBytesPersec {
            get {
                return this._iOWriteBytesPersec;
            }
            set {
                this._iOWriteBytesPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property IOWriteOperationsPersec
        /// </summary>
        public virtual ulong IOWriteOperationsPersec {
            get {
                return this._iOWriteOperationsPersec;
            }
            set {
                this._iOWriteOperationsPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property Name
        /// </summary>
        public virtual string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        /// <summary>
        /// Represents the property PageFaultsPersec
        /// </summary>
        public virtual uint PageFaultsPersec {
            get {
                return this._pageFaultsPersec;
            }
            set {
                this._pageFaultsPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property PageFileBytes
        /// </summary>
        public virtual ulong PageFileBytes {
            get {
                return this._pageFileBytes;
            }
            set {
                this._pageFileBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property PageFileBytesPeak
        /// </summary>
        public virtual ulong PageFileBytesPeak {
            get {
                return this._pageFileBytesPeak;
            }
            set {
                this._pageFileBytesPeak = value;
            }
        }
        
        /// <summary>
        /// Represents the property PercentPrivilegedTime
        /// </summary>
        public virtual ulong PercentPrivilegedTime {
            get {
                return this._percentPrivilegedTime;
            }
            set {
                this._percentPrivilegedTime = value;
            }
        }
        
        /// <summary>
        /// Represents the property PercentProcessorTime
        /// </summary>
        public virtual ulong PercentProcessorTime {
            get {
                return this._percentProcessorTime;
            }
            set {
                this._percentProcessorTime = value;
            }
        }
        
        /// <summary>
        /// Represents the property PercentUserTime
        /// </summary>
        public virtual ulong PercentUserTime {
            get {
                return this._percentUserTime;
            }
            set {
                this._percentUserTime = value;
            }
        }
        
        /// <summary>
        /// Represents the property PoolNonpagedBytes
        /// </summary>
        public virtual uint PoolNonpagedBytes {
            get {
                return this._poolNonpagedBytes;
            }
            set {
                this._poolNonpagedBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property PoolPagedBytes
        /// </summary>
        public virtual uint PoolPagedBytes {
            get {
                return this._poolPagedBytes;
            }
            set {
                this._poolPagedBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property PriorityBase
        /// </summary>
        public virtual uint PriorityBase {
            get {
                return this._priorityBase;
            }
            set {
                this._priorityBase = value;
            }
        }
        
        /// <summary>
        /// Represents the property PrivateBytes
        /// </summary>
        public virtual ulong PrivateBytes {
            get {
                return this._privateBytes;
            }
            set {
                this._privateBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property ThreadCount
        /// </summary>
        public virtual uint ThreadCount {
            get {
                return this._threadCount;
            }
            set {
                this._threadCount = value;
            }
        }
        
        /// <summary>
        /// Represents the property Timestamp_Object
        /// </summary>
        public virtual ulong Timestamp_Object {
            get {
                return this._timestamp_Object;
            }
            set {
                this._timestamp_Object = value;
            }
        }
        
        /// <summary>
        /// Represents the property Timestamp_PerfTime
        /// </summary>
        public virtual ulong Timestamp_PerfTime {
            get {
                return this._timestamp_PerfTime;
            }
            set {
                this._timestamp_PerfTime = value;
            }
        }
        
        /// <summary>
        /// Represents the property Timestamp_Sys100NS
        /// </summary>
        public virtual ulong Timestamp_Sys100NS {
            get {
                return this._timestamp_Sys100NS;
            }
            set {
                this._timestamp_Sys100NS = value;
            }
        }
        
        /// <summary>
        /// Represents the property VirtualBytes
        /// </summary>
        public virtual ulong VirtualBytes {
            get {
                return this._virtualBytes;
            }
            set {
                this._virtualBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property VirtualBytesPeak
        /// </summary>
        public virtual ulong VirtualBytesPeak {
            get {
                return this._virtualBytesPeak;
            }
            set {
                this._virtualBytesPeak = value;
            }
        }
        
        /// <summary>
        /// Represents the property WorkingSet
        /// </summary>
        public virtual ulong WorkingSet {
            get {
                return this._workingSet;
            }
            set {
                this._workingSet = value;
            }
        }
        
        /// <summary>
        /// Represents the property WorkingSetPeak
        /// </summary>
        public virtual ulong WorkingSetPeak {
            get {
                return this._workingSetPeak;
            }
            set {
                this._workingSetPeak = value;
            }
        }
    }
}
